"""
This type stub file was generated by pyright.
"""

class Bitmath:
    value: float
    def __init__(self, value: int) -> None:
        ...
    
    def to_Byte(self) -> Bitmath:
        ...
    
    def __add__(self, other: Bitmath) -> Bitmath:
        ...
    
    def __sub__(self, other: Bitmath) -> Bitmath:
        ...
    
    def __lt__(self, other: Bitmath) -> bool:
        ...
    
    def __le__(self, other: Bitmath) -> bool:
        ...
    
    def __gt__(self, other: Bitmath) -> bool:
        ...
    
    def __ge__(self, other: Bitmath) -> bool:
        ...
    
    def __eq__(self, other: Bitmath) -> bool:
        ...
    
    def __ne__(self, other: Bitmath) -> bool:
        ...
    


class MiB(Bitmath):
    def __init__(self, value: int) -> None:
        ...
    


class Byte(Bitmath):
    def __init__(self, value: int) -> None:
        ...
    


def parse_string(s: str) -> Bitmath:
    ...

